### ISSUE TITLE
License is non-free - please consider relicensing as plain MIT license

### ISSUE THREAD

**Issue by jonassmedegaard** [oli-obk/pandoc-ast#18]
Hi,

Thank you for contributing this project to the free software community.
I would like to package this for official inclusion with the Debian operating system, but unfortunately your choice of licensing blocks that: Debian does not allow discrimination of audience.

I think I understand what you are getting at when you declare that your work "may not be used in any System whose intent is harm any person's privacy, body or mind".  Personally I have in the past found a similar appeal for licenses excluding various classes of assholes. I have since been convinced that although I want to contribute to a *better* world, not any world, choosing a discriminating license does not really help with that, because of how the legal system works: It is extremely difficult to nail those bastards in the court of law (because they are slippery - e.g. form separate companies for different tasks) and extremely eady to accidentally harm those unintented (users need to *ensure* that they comply with the license, which is difficult.

Please reconsider.

**Comment by oli-obk** [comment]
I just found it funny and never intended for this crate to be widely used.

I'd happily relicense my own contributions. Not sure we'll be able to reach other contributors.

Note that I am not really maintaining this crate, so if you want to include it in debian, it's likely not going to work well with the pandoc version being shipped. This crate has almost no tests and no useful CI. I don't think it meets the bar of anything but hobby projects that don't want to write out all those pandoc structures for parsing them from json.

**Comment by jonassmedegaard** [comment]
Thank you for showing interest in changing license. That gives me hope.

My interest is in packaging not only `pandoc-ast` but also `pandoc-filter-diagram` which makes use of it (and possibly also `subplot` which is related to `pandoc-filter-diagram`).  I do not consider `pandoc-ast` only a toy, but hope to be able to help patch it to handle newer releases of Pandoc (which I have maintained for Debian [for more than 14 years](https://tracker.debian.org/news/268115/accepted-pandoc-121-1-source-all-amd64/).

I will try reach out to the 8 persons who has contributed to the project besides you, to ask for their permission for relicensing...

**Comment by jonassmedegaard** [comment]
@filiparag, @xuhongxu96, @FredeEB, @Rufflewind, @VoreckLukas, @xfbs, @joseluiscd, @sbarral  - would you be ok with relicensing your contributions for this project ~as~ under plain MIT license?

**Comment by Rufflewind** [comment]
> would you be ok with relicensing your contributions for this project as under plain MIT license?

Yes.

**Comment by FredeHoey** [comment]
I'm fairly sure that there's no reminiscence of my contributions left in
this repo but I personally think that the more MIT licensed software out
there the better

**Comment by joseluiscd** [comment]
> would you be ok with relicensing your contributions for this project ~as~ under plain MIT license?

 Yes.

**Comment by xfbs** [comment]
> would you be ok with relicensing your contributions for this project as under plain MIT license?

Sure! Happy to relicense my tiny contribution :)

**Comment by filiparag** [comment]
> Would you be ok with relicensing your contributions for this project ~as~ under plain MIT license?

Fine by me 👍🏻

**Comment by sbarral** [comment]
> would you be ok with relicensing your contributions for this project under plain MIT license?

Yes, no problem on my side.

**Comment by Overloader6** [comment]
Fine by me as well, I just fixed a bug that was anoying to me lol

**Comment by jonassmedegaard** [comment]
Seems all potential copyright holders have approved relicensing to MIT by now.

@oli-obk: Please (if you agree with my assessment, obviously) relicense the project to be licensed under plain MIT license, and (preferrably after also addressing #17 ) tag as a formal release.

**Comment by oli-obk** [comment]
done
