### ISSUE TITLE
Update pandoc-ast for 1.20 of pandoc-api-version

### ISSUE THREAD

**Issue by thor** [oli-obk/pandoc-ast#5]
Per the following instructions
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[1, 20]`,
 right: `[1, 17]`: please file a bug report against `pandoc-ast` to update for the newest pandoc version', /home/thor/.cargo/registry/src/github.com-1ecc6299db9ec823/pandoc_ast-0.7.2/src/lib.rs:33:9
```
I've come to file a bug for updating the supported version to 1.20.

Is there any further information you'd like me to provide in addition?

**Comment by oli-obk** [comment]
Nope, thanks! I'll try to set up an environment for working with 1.20 and then update `pandoc-ast`

**Comment by thor** [comment]
FWIW @oli-obk, I did a quick https://github.com/thor/pandoc-ast/commit/b2b2a8896298ff90ea58f554bf2c654aee1fb436 to get around it, and it worked fine for my purposes. (I also updated Cargo.toml, but I see I haven't pushed that.)

**Comment by oli-obk** [comment]
hmm.. maybe we can change the check to a range, and allow 1.17-1.20? Idk, I haven't checked the changelog of pandoc, but often the changes are minimal.

**Comment by thor** [comment]
Judging by #6, I'll go ahead and close this as "done".
