### ISSUE TITLE
Update pandoc-ast to 1.21

### ISSUE THREAD

**Issue by FredeHoey** [oli-obk/pandoc-ast#6]
The ast has been updated to 1.21, which means the assertion mentioned in #5 is failing :+1:

**Comment by lrosenthol** [comment]
found the same thing - and happy to help with PR

**Comment by oli-obk** [comment]
Yes, a PR would be great. We should probably change the assertion to handling all versions up to `1.21`

**Comment by sbarral** [comment]
Declaring support for `1.21` may have been a bit premature, it looks like the table serialization format has changed.

This simple table:

```
| A | B |  
|---|---|
| a | b |
```

works fine with pandoc `2.9.2` but triggers the following `Serde` error with pandoc `2.10.1`:
```
thread 'main' panicked at 'json is not in the pandoc format: Error("invalid type: string \"\", expected adjacently tagged enum Inline", line: 231, column: 5)
```
This is presumably related to pandoc [#1024](https://github.com/jgm/pandoc/issues/1024).
