### ISSUE TITLE
Pandoc-ast has no access to info about Pandoc

### ISSUE THREAD

**Issue by lrosenthol** [oli-obk/pandoc-ast#7]
One of the most important things to me when I write Lua filters for Pandoc is having the output format available, so that I can have one set of code that just varies at specific points based on the output format.  This information isn't available currently.

I looked at exposing it in various ways, but the biggest blocker right now seems to be the use of a static closure so that I can't reference any local vars (such as info extracted from the rust-Pandoc crate).

One "shortcut" would be to make the `to_json` and `from_json` methods public - and then use them directly instead of using the `filter` method (with or without closure).

Thoughts??

**Comment by oli-obk** [comment]
You don't need the `to_json` and `from_json` methods. You can just use serde directly, so `let p: Pandoc = serde_json::from_str(s).unwrap();` will give you the pandoc object directly and `serde_json::to_string(&p).unwrap()` will give you a json string again.
