### ISSUE TITLE
Update pandoc-ast to 1.22

### ISSUE THREAD

**Issue by joseluiscd** [oli-obk/pandoc-ast#9]
Pandoc's AST has been upgraded to 1.22. The support for 1.21(#6) is still limited, as this project hasn't introduced the new table block format and the `Underline` inline variant. This changes are still present in 1.22. 

Also, pandoc-types 1.22 (as seen in the changelog) includes the use of "untagged JSON encoding for single-constructor types".

I have just forked the project to introduce the new tables and the `Underline`. I use cargo features to switch between versions of the `Table` variant. More details on the upcoming pull request (it still needs testing).

**Comment by oli-obk** [comment]
I'm not really using this anymore, so I'd definitely appreciate help from someone who can test it on real input!
